# Book settings
title: DATA 301
author: Firas Moosvi
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md", "source material","unused/*", "binary files/*"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  navbar_number_sections : false
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  baseurl : "https://firas.moosvi.com/courses/2022_WT2/data301"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: true
    # utterances:
    #   repo: "ubco-cmps/data301_course"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/ubco-cmps/data301_course
  path_to_book : ""
  branch       : main

sphinx:
  extra_extensions:
    - sphinx_thebe
    - jupyterlite_sphinx
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    # html_theme_options:
    #   show_navbar_depth: 2
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - substitution
    myst_substitutions:
      INSTRUCTOR: "Dr. Firas Moosvi (he/his/him)"
      PRONOUNCE: "[Fur-az Moose-vee](https://namedrop.io/firasmoosvi)"
      OFFICE: "SCI 393"
      PHONE: "N/A"
      COURSE_CODE: "DATA 301"
      SECTION: "001"
      CREDITS: "3"
      TITLE: "Introduction to Data Analytics"
      PREREQS: "Either (a) third-year standing, or (b) one of COSC 111 or COSC 122."
      COREQS: "None"
      TERM: "2022 Winter Term 2"
      ROOM: "EME 0050"
      MEETING_TIMES: "Monday, Wednesday, Friday 10-11 AM"
      GRACE_PERIOD: "48 hour"
      W_DATE_1: "11:59 PDT on January 23, 2023"
      W_DATE_2: "11:59 PDT on March 24, 2023"
      W_DATE_3: "March 24, 2023"
      EXAM_PERIOD: "Monday, April 17 - Friday, April 28"
      CANVAS_ID: "107737"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID"
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      LAB_SCHEDULE_HERE: "[Lab Schedule here](https://courses.students.ubc.ca/cs/courseschedule?tname=subj-course&course=301&campuscd=UBCO&dept=DATA&pname=subjarea)"
      ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/data301/2022_WT2/"
      FORUM_LINK: "[Ed Discussion (sign up using your cwl@student.ubc.ca email here)](https://edstem.org/us/join/83aTXJ)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410)"
      FORMAT: "Lectures and Labs will all be running in-person in this course."
      ASSOCIATE_HEAD: "Dr. Yves Lucet [yves.lucet@ubc.ca](mailto:yves.lucet@ubc.ca) or the Department Head Dr. John Braun at [cmps.depthead@ubc.ca](cmps.depthead@ubc.ca)"
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0824TfIWX0twm5o?course=data301&term=2022_WT2)"
      TEXTBOOK: "We will not be needing a textbook for this course as you will be provided all the notes you need via the course website."